server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/questionnaire
    username: postgres
    password: 123456

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true